services:
  bossfinal.server:
    user: root
    image: ${DOCKER_REGISTRY-}bossfinalserver
    build:
      context: .
      dockerfile: BossFinal.Server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:5000
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=simplepassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificate:/https
    ports:
      - "5000:5000"
    networks:
      - app-network
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: $USER
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: $NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: